nstBASIC: interpreter.h File Reference
interpreter.h File Reference
System specifications, global variables and function prototypes.
Functions
uint16_t get_linenumber (void)
Get current line number.
void basic_init (void)
Initialization of language interpreter.
void interpreter (void)
The interpreter main loop.
Detailed Description
System specifications, global variables and function prototypes.
Most of the macros in this file play a decisive role in what this system can achieve! The program memory size determines the maximum size of user programs, while the stack size determines the maximum number of nested function calls.
Function Documentation
void basic_init (void)
Initialization of language interpreter.
This function initializes pointers used by the interpreter and prints a welcome message along with the memory size.
References newline(), printmsg(), and printnum().
Referenced by main().
uint16_t get_linenumber (void)
Get current line number.
This function scans current line and looks for a valid line number.
Note:
Scanning of current line begins at the character pointed by text_ptr.
Returns
The current line number.
References ignorespace().
Referenced by interpreter().
void interpreter (void)
The interpreter main loop.
This function examines user input and determines if the last line entered was a command or a program line. In the first case, the command is executed immediately. In the second case, the line read is merged with the rest of the program and into appropriate position.
References error_message(), execution(), find_line(), get_line(), get_linenumber(), ignorespace(), insert_line(), move_line(), prep_line(), remove_line(), and warm_reset().
Referenced by main().