nstBASIC: interpreter.c File Reference
interpreter.c File Reference
Get user input, search for commands and execute them.
Functions
static uint8_t execution (void)
Execute specified line.
static void warm_reset (void)
Perform a warm-reset.
static void insert_line (LINE_LENGTH chars_to_copy)
Insert new line in the program.
static void remove_line (void)
Remove line from program.
static void move_line (void)
Move line at the end of program memory.
static LINE_LENGTH prep_line (void)
Prepare line for merging with the program.
static void error_message (void)
Print appropriate error mesage.
uint16_t get_line_numberber (void)
Get current line number.
void basic_init (void)
Initialization of language interpreter.
void interpreter (void)
The interpreter main loop.
Detailed Description
Get user input, search for commands and execute them.
The functions in this file form the core of the interprter, which processes user input and/or programs. Every line entered by the user, that starts with a valid line-number, is considered part of the currently active program and is stored at the appropriate position in program memory. If the newly entered line does not start with a line-number, it is executed immediately.
Note:
Although the functions in this file perform some kind of parsing (syntactic analysis), they are kept separately from the main parser functions. The interpreter functions determine the state of the whole system, they run programs and call other functions, that execute single commands. They do not evaluate expressions or check the syntax of given commands. In other words, the interpreter could be seen as a manager/supervisor and the parser as one of those who do the dirty work. :)
Function Documentation
void basic_init (void)
Initialization of language interpreter.
This function initializes pointers used by the interpreter and prints a welcome message along with the memory size.
References newline(), printmsg(), printnum(), prog_end_ptr, program_space, stack_limit, stack_ptr, and variables_ptr.
Referenced by main().
static void error_message (void) static
Print appropriate error mesage.
This function resets text and background color and prints an error message.
Note:
The message is indicated by the global variable error_code.
References error_code, line_ptr, newline(), paper_color(), printline(), printmsg(), printmsg_noNL(), text_color(), and text_ptr.
Referenced by interpreter().
static uint8_t execution (void) static
Execute specified line.
This function executes the current line. A helper function (scantable()) looks for the presence of any command and the huge switch block executes the said command. When a program is running, this function loops over and keeps executing one line after the other.
Note:
The current line begins at the character pointed by text_ptr. When running a program, text_ptr is advanced automatically.
Returns
The post-execution status. See EXECUTION_STATUS enumerator.
Note:
CMD_UNKNOWN is initialy treated as an assignement and the case of just being some syntactic error / mispelling is examined later.
References break_test(), do_beep(), error_code, fx_delay_ms(), ignorespace(), line_ptr, parse_expr_s1(), printmsg(), prog_end_ptr, scantable(), sys_config, and text_ptr.
Referenced by interpreter().
uint16_t get_line_numberber (void)
Get current line number.
This function scans current line and looks for a valid line number.
Note:
Scanning of current line begins at the character pointed by text_ptr.
Returns
The current line number.
References ignorespace(), and text_ptr.
Referenced by interpreter().
static void insert_line (LINE_LENGTH chars_to_copy) static
Insert new line in the program.
This function calculates the space needed by the new line and moves existing code accordingly, so that the new line will fit.
Note:
The position at which the new line should be inserted, is specified by the text_ptr pointer.
References prog_end_ptr, and text_ptr.
Referenced by interpreter().
void interpreter (void)
The interpreter main loop.
This function examines user input and determines if the last line entered was a command or a program line. In the first case, the command is executed immediately. In the second case, the line read is merged with the rest of the program and into appropriate position.
References break_flow, error_code, error_message(), execution(), find_line(), get_line(), get_line_numberber(), ignorespace(), insert_line(), line_number, line_ptr, move_line(), prep_line(), prog_end_ptr, program_space, remove_line(), sys_config, text_ptr, uppercase(), and warm_reset().
Referenced by main().
static void move_line (void) static
Move line at the end of program memory.
This function moves the newly entered line to the end of program memory. It is executed whenever the user enters a new line and prior to the interpretation / execution.
References prog_end_ptr, text_ptr, and variables_ptr.
Referenced by interpreter().
static LINE_LENGTH prep_line (void) static
Prepare line for merging with the program.
This function calculates the memory space needed for the storing of line, accounting fot the line number as well.
References line_number, and text_ptr.
Referenced by interpreter().
static void remove_line (void) static
Remove line from program.
This function removes a line from the program and moves over the remaining code.
Note:
The line to be deleted is determined by the text_ptr pointer.
References line_number, and prog_end_ptr.
Referenced by interpreter().
static void warm_reset (void) static
Perform a warm-reset.
This function resets program-memory pointer and enables cursor and scrolling.
References line_ptr, printmsg(), program_space, and stack_ptr.
Referenced by interpreter().