nstBASIC: io.h File Reference
io.h File Reference
Peripheral communication commands and the expected prototypes.
Functions
void kb_decode (uint8_t sc)
Keyboard data decoding.
void put_kb_buffer (uint8_t chr)
Put incoming data to keyboard-buffer.
void init_io (void)
Microcontroiller peripheral initialization.
void init_kb (void)
Setup communication with keyboard.
void do_beep (void)
BEEP or flash the LED.
void uart_ansi_rst_clr (void)
Reset terminal attached to serial port.
void uart_ansi_move_cursor (uint8_t row, uint8_t col)
Move cursor on attached terminal.
void text_color (uint8_t color)
Change on-screen text colour.
void paper_color (uint8_t color)
Change on-screen background colour.
void locate_cursor (uint8_t line, uint8_t column)
Move cursor to arbitrary location.
void put_pixel (uint8_t x, uint8_t y, uint8_t color)
Draw a pixel on the screen.
void send_to_apu (uint8_t cbyte)
Send character to sound controller.
int putchar_ser (char c, FILE *stream)
Send character to device attched on serial port.
int getchar_ser (FILE *stream)
Get character from device attched on serial port.
int putchar_phy (char c, FILE *stream)
Send character to VGA controller.
int getchar_phy (FILE *stream)
Get character from keyboard.
int putchar_rom (char c, FILE *stream)
Put character in EEPROM.
int getchar_rom (FILE *stream)
Get character in EEPROM.
Variables
FILE stream_physical
uint16_t eeprom_ptr
uint8_t break_flow
Detailed Description
Peripheral communication commands and the expected prototypes.
The macros in this file correspond to ASCII codes or other, special values, used for the communication with the peripherals. None of them should be tweaked, unless the firmware for the peripherals is also updated!
Function Documentation
void do_beep (void)
BEEP or flash the LED.
This function makes a sound (beep) or flashes an LED, to inform user about an error (usually when the keyboard buffer is full).
Referenced by execution(), get_line(), kb_decode(), main(), and put_kb_buffer().
int getchar_phy (FILE * stream)
Get character from keyboard.
The default STANDARD INPUT for this system is the buffer holding the keyboard keystrokes. This function gets a character from the said buffer.
References fx_delay_ms().
int getchar_rom (FILE * stream)
Get character in EEPROM.
This function reads a character from EEPROM. It is used by the EEPROM stream.
References eeprom_ptr.
int getchar_ser (FILE * stream)
Get character from device attched on serial port.
void init_io (void)
Microcontroiller peripheral initialization.
This function configures the pins of the CPU (actually the microcontroller). It prepares the ADC, initializes the keyboard and prints some messages.
References init_kb(), stream_physical, and uart_ansi_rst_clr().
Referenced by main().
void init_kb (void)
Setup communication with keyboard.
This function configures the pins used for communicating with the keyboard and enables an interrupt for receiving the incoming data.
References break_flow.
Referenced by init_io().
void kb_decode (uint8_t sc)
Keyboard data decoding.
This functions decodes the data transmitted by the keyboard and updates some variables which hold he state of key modifiers (CAPSLOCK, NUMLOCK, SHIFT and CTRL). The array to_ascii is only used for decoding the scancodes of normal (printable) characters. The decoded data are placed in a special buffer, with the help of put_kb_buffer() function.
References break_flow, do_beep(), printmsg(), and put_kb_buffer().
Referenced by ISR().
void locate_cursor (uint8_t line, uint8_t column)
Move cursor to arbitrary location.
This function sends to the graphics subsystem the necessary control byte, along with the new location of the cursor.
void paper_color (uint8_t color)
Change on-screen background colour.
This function sends to the graphics subsystem the necessary control byte, along with the selected background colour – paper colour, anyone?
Referenced by error_message(), and main().
void put_kb_buffer (uint8_t chr)
Put incoming data to keyboard-buffer.
This function puts incomming data to a special buffer for later use. When the buffer is full, the system makes a beep sound.
References do_beep().
Referenced by kb_decode().
void put_pixel (uint8_t x, uint8_t y, uint8_t color)
Draw a pixel on the screen.
This function sends to the graphics subsystem the necessary control byte, along with data describing the new pixel (position and colour).
int putchar_phy (char chr, FILE * stream)
Send character to VGA controller.
This function sends a signle character to the graphics subsystem. If it is a printable character, it will also be transmitted through the serial port.
int putchar_rom (char chr, FILE * stream)
Put character in EEPROM.
This function writes a character in EEPROM. It is used by the EEPROM stream.
References eeprom_ptr.
int putchar_ser (char chr, FILE * stream)
Send character to device attched on serial port.
References putchar_ser().
Referenced by putchar_ser().
void send_to_apu (uint8_t cbyte)
Send character to sound controller.
This function sends a signle character to the audio subsystem.
Referenced by parse_channel(), and parse_notes().
void text_color (uint8_t color)
Change on-screen text colour.
This function sends to the graphics subsystem the necessary control byte, along with the selected "text" colour.
Referenced by error_message(), and main().
void uart_ansi_move_cursor (uint8_t row, uint8_t col)
Move cursor on attached terminal.
This function transmits a special sequrence of chartacters that moves the cursor of the terminal to a specific position.
void uart_ansi_rst_clr (void)
Reset terminal attached to serial port.
This function transmits a special sequrence of chartacters that is interpreted as a request to reset the terminal.
Referenced by init_io().
Variable Documentation
uint8_t break_flow
This variable signifies whether the user has pressed the BREAK button or CTR+c.
Referenced by break_test(), init_kb(), interpreter(), ISR(), and kb_decode().
uint16_t eeprom_ptr
Pointer to current character in EEPROM space. This is mainly used for sweeping the available memory space, while reading or writing.
Referenced by getchar_rom(), and putchar_rom().
FILE stream_physical
Streams for data transfer to and from various subsystems:
srteam_serial: SERIAL port (9600bps)
srteam_eeprom: embedded EEPROM memory (2Kb)
srteam_physical: keyboard and graphics card
Referenced by init_io().