nstBASIC: main.c File Reference
main.c File Reference
Functions that would fit in no other file :)
Functions
int main (void)
Program entry point – the main function.
void read_serial_eeprom (FILE input_stream)
Read from SERIAL or EEPROM.
void get_line (void)
Get line(s) from EEPROM, SERIAL or STDIO.
void push_byte (uint8_t byte_to_push)
Push a byte in the STACK.
uint8_t pop_byte (void)
Pop a byte from the STACK.
uint8_t * find_line (void)
void ignorespace (void)
Ignore whitespace characters.
void uppercase (void)
Transform to uppercase.
void fx_delay_ms (uint16_t ms)
Busy-delay functions.
uint8_t break_test (void)
Check if BREAK button was pressed.
int16_t str_to_num (uint8_t *strptr)
Transform string representation to numeric.
Detailed Description
Functions that would fit in no other file :)
Function Documentation
uint8_t break_test (void)
Check if BREAK button was pressed.
References break_flow.
Referenced by execution().
uint8_t* find_line (void)
References line_number, prog_end_ptr, and program_space.
Referenced by interpreter().
void fx_delay_ms (uint16_t ms)
Busy-delay functions.
Referenced by execution(), and getchar_phy().
void get_line (void)
Get line(s) from EEPROM, SERIAL or STDIO.
Get one or more lines, depending on the selected input. If the system configuration (sys_config) dictates that new data should be received from EEPROM or SERIAL (this happens when loading programs from either source) the function will keep getting lines until a NULL character is received. If new data is to be received from STDIN (the user himself) the fuinction will only get a single line.
References do_beep(), newline(), prog_end_ptr, read_serial_eeprom(), sys_config, text_ptr, and variables_ptr.
Referenced by interpreter().
void ignorespace (void)
Ignore whitespace characters.
If current character (indicated by text_ptr pointer) is SPACE or TAB advance pointer and move to next character
References text_ptr.
Referenced by execution(), get_line_numberber(), interpreter(), parse_expr_s3(), parse_expr_s4(), and scantable().
int main (void)
Program entry point – the main function.
References basic_init(), do_beep(), init_io(), interpreter(), paper_color(), printmsg(), and text_color().
uint8_t pop_byte (void)
Pop a byte from the STACK.
References stack_ptr.
Referenced by printnum().
void push_byte (uint8_t byte_to_push)
Push a byte in the STACK.
References stack_ptr.
Referenced by printnum().
void read_serial_eeprom (FILE input_stream)
Read from SERIAL or EEPROM.
Keep reading from SERIAL or eeprom until a NULL character is received.
References sys_config, and text_ptr.
Referenced by get_line().
int16_t str_to_num (uint8_t * strptr)
Transform string representation to numeric.
void uppercase (void)
Transform to uppercase.
Transform everything but strings to uppercase.
References prog_end_ptr.
Referenced by interpreter().