nstBASIC: parser.c File Reference
parser.c File Reference
Syntactic analysis and expression evaluation.
Functions
static int16_t parse_expr_s2 (void)
Search for subtraction or addition operators.
static int16_t parse_expr_s3 (void)
Search for multiplication or division operators.
static int16_t parse_expr_s4 (void)
Search for numbers, variables or functions.
static uint8_t get_note (void)
Get single note.
static uint8_t get_effect (void)
Search for an effect mark.
static uint8_t get_duration (void)
Get duration value.
static uint8_t get_octave (void)
Get octave.
int8_t scantable (const uint8_t *table)
Search for any string in specified table.
void parse_channel (void)
Search for channel number.
void parse_notes (void)
Search for notes.
int16_t parse_expr_s1 (void)
Search for relational operators.
Detailed Description
Syntactic analysis and expression evaluation.
The functions parse_expr_s# call each other recursivelly, until the given expression is evaluated. The first of them handles relational operators, the second one handles additions and sutractions, the third handles multiplications and divisions, while the fourth substitutes variables with the respective values, calls other arithmetic functions, or could even start the whole 'chain' of parsing from the beginning, in order to evaluate a sub-expression. The representation of a mathematical expression in the form of a tree could help understand why this works and how the operator precedence is honored. The rest functions parse the special strings used for describing sequences of notes and in essence, complete melodies.
Function Documentation
static uint8_t get_duration (void) static
Get duration value.
This function examines current line and looks for the string representation of a note duration.
Note:
Scanning begins at the character pointed to by text_ptr.
Returns
A number indicating the defined duration.
References error_code, and text_ptr.
Referenced by parse_notes().
static uint8_t get_effect (void) static
Search for an effect mark.
This function examines current line and searches for a valid effect mark.
Note:
Scanning begins at the character pointed to by text_ptr.
Returns
A number indicating the defined effect.
References text_ptr.
Referenced by parse_notes().
static uint8_t get_note (void) static
Get single note.
This function examines current line and looks for the string representation of a note.
Note:
Scanning begins at the character pointed to by text_ptr.
Returns
A number indicating the defined note.
References error_code, and text_ptr.
Referenced by parse_notes().
static uint8_t get_octave (void) static
Get octave.
This function examines current line and looks for the string representation of an octave number.
Note:
Scanning begins at the character pointed to by text_ptr.
Returns
A number indicating the defined octave.
References error_code, and text_ptr.
Referenced by parse_notes().
void parse_channel (void)
Search for channel number.
This function examines current line and searches for sound-channel number.
Note:
Scanning begins at the character pointed to by text_ptr.
References error_code, send_to_apu(), and text_ptr.
int16_t parse_expr_s1 (void)
Search for relational operators.
This function examines current line and searches for any relational operator.
Note:
Scanning begins at the character pointed to by text_ptr.
Returns
The result from the evaluation of the whole expression.
References error_code, parse_expr_s2(), and scantable().
Referenced by execution(), and parse_expr_s4().
static int16_t parse_expr_s2 (void) static
Search for subtraction or addition operators.
This function examines current line and looks for a subtraction or an addition operator.
Note:
Scanning begins at the character pointed to by text_ptr.
Returns
The result from the evaluation of the sub-expression.
References parse_expr_s3(), and text_ptr.
Referenced by parse_expr_s1().
static int16_t parse_expr_s3 (void) static
Search for multiplication or division operators.
This function examines current line and looks for a multiplication or a division operator.
Note:
Scanning begins at the character pointed to by text_ptr.
Returns
The result from the evaluation of the sub-expression.
References error_code, ignorespace(), parse_expr_s4(), and text_ptr.
Referenced by parse_expr_s2().
static int16_t parse_expr_s4 (void) static
Search for numbers, variables or functions.
This function examines current line and looks for string representations of numbers, variables and functions.
Note:
Scanning begins at the character pointed to by text_ptr.
Returns
The result from the evaluation of the sub-expression.
References error_code, ignorespace(), parse_expr_s1(), program_space, scantable(), text_ptr, and variables_ptr.
Referenced by parse_expr_s3().
void parse_notes (void)
Search for notes.
This function examines current line and searches for notes.
Note:
Scanning begins at the character pointed to by text_ptr.
References get_duration(), get_effect(), get_note(), get_octave(), and send_to_apu().
int8_t scantable (const uint8_t * table)
Search for any string in specified table.
This function scans current line and looks for any string contained in the specified array.
Note:
Scanning begins at the character pointed to by text_ptr.
Parameters
table A pointer to an array of strings, located in FLASH.
Returns
The position (index) of the detected string in array.
References ignorespace(), and text_ptr.
Referenced by execution(), parse_expr_s1(), and parse_expr_s4().