nstBASIC: parser.h File Reference
parser.h File Reference
Prototypes, macros, enumerators and global variables...
Functions
int8_t scantable (const uint8_t *table)
Search for any string in specified table.
void parse_channel (void)
Search for channel number.
void parse_notes (void)
Search for notes.
int16_t parse_expr_s1 (void)
Search for relational operators.
Detailed Description
Prototypes, macros, enumerators and global variables...
The COMMANDS enumerator contains a member for each command supported by the language. The memebers of the enumerator appear in the same order as the corresponding commands, in the commands table (see parser.c). The last member of the enumerator is used for assignments (some_variable = some_value) which do not use some special command. I other words, CMD_ASSIGNMENT corresponds to no entry in the commands table!
Function Documentation
void parse_channel (void)
Search for channel number.
This function examines current line and searches for sound-channel number.
Note:
Scanning begins at the character pointed to by text_ptr.
References send_to_apu().
int16_t parse_expr_s1 (void)
Search for relational operators.
This function examines current line and searches for any relational operator.
Note:
Scanning begins at the character pointed to by text_ptr.
Returns
The result from the evaluation of the whole expression.
References parse_expr_s2(), and scantable().
Referenced by execution(), and parse_expr_s4().
void parse_notes (void)
Search for notes.
This function examines current line and searches for notes.
Note:
Scanning begins at the character pointed to by text_ptr.
References get_duration(), get_effect(), get_note(), get_octave(), and send_to_apu().
int8_t scantable (const uint8_t * table)
Search for any string in specified table.
This function scans current line and looks for any string contained in the specified array.
Note:
Scanning begins at the character pointed to by text_ptr.
Parameters
table A pointer to an array of strings, located in FLASH.
Returns
The position (index) of the detected string in array.
References ignorespace().
Referenced by execution(), parse_expr_s1(), and parse_expr_s4().