nstBASIC: printing.c File Reference
printing.c File Reference
Message and other data printing.
Functions
void printstr (char *string, FILE *stream)
Print specified string.
void printnum (int16_t number, FILE *stream)
Print specified integer number.
void printmsg_noNL (const uint8_t *message, FILE *stream)
Print selected message from FLASH (without new-line)
void printmsg (const uint8_t *message, FILE *stream)
Print selected message from FLASH (with new-line)
void printline (uint8_t *line, FILE *stream)
Print a program line.
void newline (FILE *stream)
Print a NEW LINE character.
uint8_t print_string (void)
Print a user defined string (enclosed in quotes)
void debug_print (uint8_t chr)
Print the specified character (only used for debug purposes)
Detailed Description
Message and other data printing.
The functions in this file can print messages, numbers, program listings or arbitrary (user defined) strings on the screen, on some terminal through the serial port or on the EEPROM. This flexibility is achieved with the use of relevant streams, defined in io.c. Each of these streams is accompanied by functions that handle low-level IO cimmunication with the corresponding device.
Function Documentation
void debug_print (uint8_t chr)
Print the specified character (only used for debug purposes)
void newline (FILE * stream)
Print a NEW LINE character.
Referenced by basic_init(), error_message(), get_line(), printline(), and printmsg().
uint8_t print_string (void)
Print a user defined string (enclosed in quotes)
Note:
The opening delimiter of the string is pointed to by text_ptr.
References text_ptr.
void printline (uint8_t * line, FILE * stream)
Print a program line.
References newline(), and printnum().
Referenced by error_message().
void printmsg (const uint8_t * message, FILE * stream)
Print selected message from FLASH (with new-line)
References newline(), and printmsg_noNL().
Referenced by basic_init(), error_message(), execution(), kb_decode(), main(), and warm_reset().
void printmsg_noNL (const uint8_t * message, FILE * stream)
Print selected message from FLASH (without new-line)
Referenced by error_message(), and printmsg().
void printnum (int16_t number, FILE * stream)
Print specified integer number.
References pop_byte(), and push_byte().
Referenced by basic_init(), and printline().
void printstr (char * string, FILE * stream)
Print specified string.